### ISSUE TITLE
Checklist

### ISSUE THREAD

**Issue by Tamarunghi** [Tamarunghi/DEV006-md-links#2]
- [ ] Leer sobre a función en _Readme_
- [ ] Averiguar sobre _promise_ y _new Promise_
- [ ] Averiguar sobre _fs_
- [ ] Averiguar sobre _fs.existsSync_
- [ ] Hacer la _función_
